---
- name: Install fluentd package
  yum:
    name: '{{ fluentd_package_name }}'
    state: latest
  when: manage_packages|default(true)
  notify: restart fluentd

- name: Install oVirt fluentd plugins
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - '{{ fluentd_ovirt_plugin_packages }}'
  when:
    - manage_packages|default(true)
    - inventory_hostname in groups.engine
  notify: restart fluentd
