---
- name: Initial validations
  hosts: localhost

  roles:
    - role: logging/roles/initial-validations

- name: Configure Metrics
  hosts: localhost

  roles:
    - role: logging/roles/fluentd
      when: hostvars['localhost']['failed_validation'] is undefined
