---
- name: Initial validations
  hosts: localhost

  roles:
    - role: logging/roles/initial-validations

- name: Configure Logging
  hosts: all

  roles:
    - role: logging/roles/rsyslog
      when: logging_collector == logging_collector_rsyslog

    - role: logging/roles/fluentd/initial-validations
      when: logging_collector == logging_collector_fluentd

    - role: logging/roles/fluentd
      when:
        - logging_collector == logging_collector_fluentd
        - failed_validation is undefined

